FROM node:20-alpine AS build-stage
WORKDIR /app

# Define Build Arguments
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_KEY
ARG VITE_SUPABASE_SECRET
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_EMAILJS_EMAIL
ARG VITE_EMAILJS_KEY
ARG VITE_EMAILJS_SERVICE_ID

# Set Environment Variables for the build process
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_KEY=$VITE_SUPABASE_KEY
ENV VITE_SUPABASE_SECRET=$VITE_SUPABASE_SECRET
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_EMAILJS_EMAIL=$VITE_EMAILJS_EMAIL
ENV VITE_EMAILJS_KEY=$VITE_EMAILJS_KEY
ENV VITE_EMAILJS_SERVICE_ID=$VITE_EMAILJS_SERVICE_ID

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]